name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or master if that's your default branch
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build Website
        run: |
          # If you're using any build tools like npm, gulp, etc., add commands here
          echo "Build your website (if needed)"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Adjust if your website is in a subfolder
          
